/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.exportSymbol('proto.com.netifi.access.keys.AccessKey', null, global);
goog.exportSymbol('proto.com.netifi.access.keys.AccessKeyName', null, global);
goog.exportSymbol('proto.com.netifi.access.keys.AccessKeyParameters', null, global);
goog.exportSymbol('proto.com.netifi.access.keys.AccessToken', null, global);
goog.exportSymbol('proto.com.netifi.access.keys.AccessTokenInfo', null, global);
goog.exportSymbol('proto.com.netifi.access.keys.AccessTokenInfoChangesEvent', null, global);
goog.exportSymbol('proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.Type', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.netifi.access.keys.AccessKeyName = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.netifi.access.keys.AccessKeyName, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.netifi.access.keys.AccessKeyName.displayName = 'proto.com.netifi.access.keys.AccessKeyName';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.netifi.access.keys.AccessKeyName.prototype.toObject = function(opt_includeInstance) {
  return proto.com.netifi.access.keys.AccessKeyName.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.netifi.access.keys.AccessKeyName} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.netifi.access.keys.AccessKeyName.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.netifi.access.keys.AccessKeyName}
 */
proto.com.netifi.access.keys.AccessKeyName.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.netifi.access.keys.AccessKeyName;
  return proto.com.netifi.access.keys.AccessKeyName.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.netifi.access.keys.AccessKeyName} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.netifi.access.keys.AccessKeyName}
 */
proto.com.netifi.access.keys.AccessKeyName.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.netifi.access.keys.AccessKeyName.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.netifi.access.keys.AccessKeyName.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.netifi.access.keys.AccessKeyName} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.netifi.access.keys.AccessKeyName.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.com.netifi.access.keys.AccessKeyName.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.netifi.access.keys.AccessKeyName.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.netifi.access.keys.AccessKey = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.netifi.access.keys.AccessKey, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.netifi.access.keys.AccessKey.displayName = 'proto.com.netifi.access.keys.AccessKey';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.netifi.access.keys.AccessKey.prototype.toObject = function(opt_includeInstance) {
  return proto.com.netifi.access.keys.AccessKey.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.netifi.access.keys.AccessKey} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.netifi.access.keys.AccessKey.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.netifi.access.keys.AccessKey}
 */
proto.com.netifi.access.keys.AccessKey.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.netifi.access.keys.AccessKey;
  return proto.com.netifi.access.keys.AccessKey.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.netifi.access.keys.AccessKey} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.netifi.access.keys.AccessKey}
 */
proto.com.netifi.access.keys.AccessKey.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.netifi.access.keys.AccessKey.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.netifi.access.keys.AccessKey.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.netifi.access.keys.AccessKey} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.netifi.access.keys.AccessKey.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 key = 1;
 * @return {number}
 */
proto.com.netifi.access.keys.AccessKey.prototype.getKey = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.com.netifi.access.keys.AccessKey.prototype.setKey = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.netifi.access.keys.AccessKeyParameters = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.netifi.access.keys.AccessKeyParameters, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.netifi.access.keys.AccessKeyParameters.displayName = 'proto.com.netifi.access.keys.AccessKeyParameters';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.netifi.access.keys.AccessKeyParameters.prototype.toObject = function(opt_includeInstance) {
  return proto.com.netifi.access.keys.AccessKeyParameters.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.netifi.access.keys.AccessKeyParameters} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.netifi.access.keys.AccessKeyParameters.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.netifi.access.keys.AccessKeyParameters}
 */
proto.com.netifi.access.keys.AccessKeyParameters.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.netifi.access.keys.AccessKeyParameters;
  return proto.com.netifi.access.keys.AccessKeyParameters.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.netifi.access.keys.AccessKeyParameters} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.netifi.access.keys.AccessKeyParameters}
 */
proto.com.netifi.access.keys.AccessKeyParameters.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.netifi.access.keys.AccessKeyParameters.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.netifi.access.keys.AccessKeyParameters.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.netifi.access.keys.AccessKeyParameters} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.netifi.access.keys.AccessKeyParameters.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.com.netifi.access.keys.AccessKeyParameters.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.netifi.access.keys.AccessKeyParameters.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 1;
 * @return {string}
 */
proto.com.netifi.access.keys.AccessKeyParameters.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.netifi.access.keys.AccessKeyParameters.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.netifi.access.keys.AccessToken = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.netifi.access.keys.AccessToken, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.netifi.access.keys.AccessToken.displayName = 'proto.com.netifi.access.keys.AccessToken';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.netifi.access.keys.AccessToken.prototype.toObject = function(opt_includeInstance) {
  return proto.com.netifi.access.keys.AccessToken.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.netifi.access.keys.AccessToken} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.netifi.access.keys.AccessToken.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, 0),
    accesstoken: msg.getAccesstoken_asB64(),
    name: jspb.Message.getFieldWithDefault(msg, 4, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.netifi.access.keys.AccessToken}
 */
proto.com.netifi.access.keys.AccessToken.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.netifi.access.keys.AccessToken;
  return proto.com.netifi.access.keys.AccessToken.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.netifi.access.keys.AccessToken} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.netifi.access.keys.AccessToken}
 */
proto.com.netifi.access.keys.AccessToken.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAccesstoken(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.netifi.access.keys.AccessToken.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.netifi.access.keys.AccessToken.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.netifi.access.keys.AccessToken} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.netifi.access.keys.AccessToken.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getAccesstoken_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int64 key = 1;
 * @return {number}
 */
proto.com.netifi.access.keys.AccessToken.prototype.getKey = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.com.netifi.access.keys.AccessToken.prototype.setKey = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bytes accessToken = 2;
 * @return {!(string|Uint8Array)}
 */
proto.com.netifi.access.keys.AccessToken.prototype.getAccesstoken = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes accessToken = 2;
 * This is a type-conversion wrapper around `getAccesstoken()`
 * @return {string}
 */
proto.com.netifi.access.keys.AccessToken.prototype.getAccesstoken_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAccesstoken()));
};


/**
 * optional bytes accessToken = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAccesstoken()`
 * @return {!Uint8Array}
 */
proto.com.netifi.access.keys.AccessToken.prototype.getAccesstoken_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAccesstoken()));
};


/** @param {!(string|Uint8Array)} value */
proto.com.netifi.access.keys.AccessToken.prototype.setAccesstoken = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional string name = 4;
 * @return {string}
 */
proto.com.netifi.access.keys.AccessToken.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.com.netifi.access.keys.AccessToken.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.com.netifi.access.keys.AccessToken.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.netifi.access.keys.AccessToken.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.netifi.access.keys.AccessTokenInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.netifi.access.keys.AccessTokenInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.netifi.access.keys.AccessTokenInfo.displayName = 'proto.com.netifi.access.keys.AccessTokenInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.com.netifi.access.keys.AccessTokenInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.netifi.access.keys.AccessTokenInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.netifi.access.keys.AccessTokenInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, 0),
    accesstokenhash: msg.getAccesstokenhash_asB64(),
    accesstokensalt: msg.getAccesstokensalt_asB64(),
    accesskeyalgo: jspb.Message.getFieldWithDefault(msg, 4, ""),
    name: jspb.Message.getFieldWithDefault(msg, 8, ""),
    description: jspb.Message.getFieldWithDefault(msg, 5, ""),
    disabled: jspb.Message.getFieldWithDefault(msg, 6, false),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.netifi.access.keys.AccessTokenInfo}
 */
proto.com.netifi.access.keys.AccessTokenInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.netifi.access.keys.AccessTokenInfo;
  return proto.com.netifi.access.keys.AccessTokenInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.netifi.access.keys.AccessTokenInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.netifi.access.keys.AccessTokenInfo}
 */
proto.com.netifi.access.keys.AccessTokenInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAccesstokenhash(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAccesstokensalt(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccesskeyalgo(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDisabled(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.netifi.access.keys.AccessTokenInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.netifi.access.keys.AccessTokenInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.netifi.access.keys.AccessTokenInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getAccesstokenhash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getAccesstokensalt_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getAccesskeyalgo();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDisabled();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 key = 1;
 * @return {number}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.getKey = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.setKey = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bytes accessTokenHash = 2;
 * @return {!(string|Uint8Array)}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.getAccesstokenhash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes accessTokenHash = 2;
 * This is a type-conversion wrapper around `getAccesstokenhash()`
 * @return {string}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.getAccesstokenhash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAccesstokenhash()));
};


/**
 * optional bytes accessTokenHash = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAccesstokenhash()`
 * @return {!Uint8Array}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.getAccesstokenhash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAccesstokenhash()));
};


/** @param {!(string|Uint8Array)} value */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.setAccesstokenhash = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes accessTokenSalt = 3;
 * @return {!(string|Uint8Array)}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.getAccesstokensalt = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes accessTokenSalt = 3;
 * This is a type-conversion wrapper around `getAccesstokensalt()`
 * @return {string}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.getAccesstokensalt_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAccesstokensalt()));
};


/**
 * optional bytes accessTokenSalt = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAccesstokensalt()`
 * @return {!Uint8Array}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.getAccesstokensalt_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAccesstokensalt()));
};


/** @param {!(string|Uint8Array)} value */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.setAccesstokensalt = function(value) {
  jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional string accessKeyAlgo = 4;
 * @return {string}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.getAccesskeyalgo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.setAccesskeyalgo = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string name = 8;
 * @return {string}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string description = 5;
 * @return {string}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bool disabled = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.getDisabled = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.setDisabled = function(value) {
  jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.setTimestamp = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.com.netifi.access.keys.AccessTokenInfo.prototype.clearTimestamp = function() {
  this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.netifi.access.keys.AccessTokenInfo.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 7) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.netifi.access.keys.AccessTokenInfoChangesEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.netifi.access.keys.AccessTokenInfoChangesEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.displayName = 'proto.com.netifi.access.keys.AccessTokenInfoChangesEvent';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.netifi.access.keys.AccessTokenInfoChangesEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    accesstokeninfo: (f = msg.getAccesstokeninfo()) && proto.com.netifi.access.keys.AccessTokenInfo.toObject(includeInstance, f),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.netifi.access.keys.AccessTokenInfoChangesEvent}
 */
proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.netifi.access.keys.AccessTokenInfoChangesEvent;
  return proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.netifi.access.keys.AccessTokenInfoChangesEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.netifi.access.keys.AccessTokenInfoChangesEvent}
 */
proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.netifi.access.keys.AccessTokenInfo;
      reader.readMessage(value,proto.com.netifi.access.keys.AccessTokenInfo.deserializeBinaryFromReader);
      msg.setAccesstokeninfo(value);
      break;
    case 2:
      var value = /** @type {!proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.netifi.access.keys.AccessTokenInfoChangesEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccesstokeninfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.netifi.access.keys.AccessTokenInfo.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.Type = {
  ADDED: 0,
  REMOVED: 1,
  UPDATED: 2
};

/**
 * optional AccessTokenInfo accessTokenInfo = 1;
 * @return {?proto.com.netifi.access.keys.AccessTokenInfo}
 */
proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.prototype.getAccesstokeninfo = function() {
  return /** @type{?proto.com.netifi.access.keys.AccessTokenInfo} */ (
    jspb.Message.getWrapperField(this, proto.com.netifi.access.keys.AccessTokenInfo, 1));
};


/** @param {?proto.com.netifi.access.keys.AccessTokenInfo|undefined} value */
proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.prototype.setAccesstokeninfo = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.prototype.clearAccesstokeninfo = function() {
  this.setAccesstokeninfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.prototype.hasAccesstokeninfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Type type = 2;
 * @return {!proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.Type}
 */
proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.prototype.getType = function() {
  return /** @type {!proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.Type} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.Type} value */
proto.com.netifi.access.keys.AccessTokenInfoChangesEvent.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


goog.object.extend(exports, proto.com.netifi.access.keys);
